### ISSUE TITLE
No module named norm2layer

### ISSUE THREAD

**Issue by zhangfudiyi** [pinguo-luhaofang/tripletloss#22]
为什么我训练好了模型后，在测试一张图片时会出现No module named norm2layer，这个原因是我没有配置好caffe吗？但是我在训练模型的时候是没问题的，并且单独使用softmax测试图片也是没问题的，为什么就会在训练好triplet模型后，去测试一张图片的时候出现这种情况，求赐教，谢谢了！不胜感激！ @pinguo-luhaofang

**Comment by pinguo-luhaofang** [comment]
@zhangfudiyi 请检查一下你的deploy文件

**Comment by zhangfudiyi** [comment]
@pinguo-luhaofang 谢谢你！我已检查过deploy和train文件，我在想这个norm2layer是你定义的网络层，我是不是需要把它添加到我的python路径下？是不是就是拷贝你的norm2layer.py文件放到caffe中的python文件夹下面呢？谢谢了！

**Comment by pinguo-luhaofang** [comment]
@zhangfudiyi 不需要放到caffe的目录下，但是需要让你运行状态下的python找得到，请参见[here](https://github.com/pinguo-luhaofang/tripletloss/blob/master/tripletloss/_init_paths.py)

**Comment by zhangfudiyi** [comment]
@pinguo-luhaofang 谢谢你！那个路径我已经改好了，但是没什么用。于是我将你的norm2layer.py文件复制到我caffe中的python文件夹下，这样运行才没出问题，但是测试一直有问题。为什么我只使用softmax模型识别率很高，但是我再加上tripletloss之后训练出来的模型测试一张图片时，识别率为0了！我训练tripletloss模型时，复制我训练好的softmax模型参数到整个网络中，在tripletloss的整过训练中，我只改变了fc9_1的 lr_mult和decay_mult，而其他层都设置为0，训练中，ap很小，an很大，但是测试一张图片时却识别率基本为0呢？求指点一下下，不胜感激！

**Comment by pinguo-luhaofang** [comment]
@zhangfudiyi tripletloss不是用于分类的。本身特征的产出已经改变了其用于分类的用途，测试用到的是verification的方法测试。

**Comment by zhangfudiyi** [comment]
@pinguo-luhaofang 这样啊！我一直用分类的去测试，主要还是我不懂，谢谢你了，感谢你抽时间帮助我，谢啦！

**Comment by tanyuan1992** [comment]
@zhangfudiyi 你训练成功了吗  用的什么模型啊

**Comment by zhangfudiyi** [comment]
@tanyuan1992 ？？？？ 不懂你意思 就按照 pinguo-luhaofang 这个来就可以了！

**Comment by wuhuaming2006** [comment]
我用sampledata 跑的，怎么老出来 IndexError: list index out of range的问题哦

**Comment by zhangfudiyi** [comment]
把输入bitch变小 原代码给的30

**Comment by wuhuaming2006** [comment]
是在config.py里面的BATCH_SIZE = 30吗？我改小了也是出现这个问题呢，这个还必须是3的倍数

**Comment by zhangfudiyi** [comment]
看代码，要改几个地方，你稍微看一下代码就知道了。个人建议代码要看懂，你就跑通的话没多大必要了，整个代码就是先用的分类(分类识别已经很高了)，再加上tripletloss。其实代码看懂了你就知道怎么办了。

**Comment by zhangfudiyi** [comment]
看代码，要改几个地方，你稍微看一下代码就知道了。个人建议代码要看懂，你就跑通的话没多大必要了，整个代码就是先用的分类(分类识别已经很高了)，再加上tripletloss。其实代码看懂了你就知道怎么办了。

**Comment by tanyuan1992** [comment]
@zhangfudiyi 我用我自己的数据集训练的一个1000分类的模型 再根据作者的步骤来走 但是Loss不收敛

**Comment by louielu1027** [comment]
@zhangfudiyi 您好，我跑的时候出现这个问题，怎么解决呢？
I0811 09:03:59.709508 13623 net.cpp:120] Setting up data
Traceback (most recent call last):
  File "/home/dl1/lvlu/10000all/tripletloss-master/tripletloss/datalayer.py", line 82, in setup
    layer_params = yaml.load(self.param_str)    
AttributeError: 'DataLayer' object has no attribute 'param_str'
Traceback (most recent call last):
  File "train.py", line 90, in <module>
    sw = SolverWrapper(solver_prototxt, output_dir,pretrained_model)
  File "train.py", line 31, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
SystemError: NULL result without error in PyObject_Call

**Comment by CharlesKung** [comment]
@louielu1027 你好...我也出现了这个问题，想请教一下是怎么解决的..
