### ISSUE TITLE
Data Layer Creating Problem

### ISSUE THREAD

**Issue by zhaoxin19** [pinguo-luhaofang/tripletloss#24]
Hi, there is a problem when creating data layer. Could you please tell me how to fix it?
I0614 14:01:23.216370  9957 layer_factory.hpp:77] Creating layer data
I0614 14:01:23.312580  9957 net.cpp:91] Creating Layer data
I0614 14:01:23.312675  9957 net.cpp:399] data -> data
I0614 14:01:23.312741  9957 net.cpp:399] data -> labels
Traceback (most recent call last):
  File "train.py", line 89, in <module>
    sw = SolverWrapper(solver_prototxt, output_dir,pretrained_model)
  File "train.py", line 30, in __init__
    self.solver = caffe.SGDSolver(solver_prototxt)
  File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 82, in setup
    layer_params = yaml.load(self.param_str_)    
AttributeError: 'DataLayer' object has no attribute 'param_str_'

**Comment by wuhuaming2006** [comment]
param_str_ 这个错了，改成param_str就好了

**Comment by zhaoxin19** [comment]
非常感谢，这个问题已经解决了，但是后面test的时候有有其他错误，麻烦您给看看？
I0614 14:30:08.994966 10091 solver.cpp:60] Solver scaffolding done.
Solving...
I0614 14:30:09.001552 10091 solver.cpp:337] Iteration 0, Testing net (#0)
Traceback (most recent call last):
  File "train.py", line 92, in <module>
    sw.train_model(max_iters)
  File "train.py", line 63, in train_model
    self.solver.step(1)     
  File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 101, in forward
    blobs = self._get_next_minibatch()
  File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 57, in _get_next_minibatch
    im_blob,labels_blob = self._get_image_blob(sample)
  File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 71, in _get_image_blob
    im = prep_im_for_blob(im)
  File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/blob.py", line 31, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by wuhuaming2006** [comment]
你测试图片格式是什么？

**Comment by zhaoxin19** [comment]
是电影抽出来的帧，jpg格式。不是人脸，跟这个有关系吗

**Comment by zhaoxin19** [comment]
测试datalayer.py 的时候会报这个错误
$ python datalayer.py
440
Traceback (most recent call last):
  File "datalayer.py", line 185, in <module>
    blob = test._get_next_minibatch()
  File "datalayer.py", line 135, in _get_next_minibatch
    while len(sample) < self._triplet:
AttributeError: TestBlobFetcher instance has no attribute '_triplet'

**Comment by wuhuaming2006** [comment]
你的sampledata.py测的吗？train_val.txt 格式是什么？

**Comment by wuhuaming2006** [comment]
_triplet 应该是还没选取triplet对

**Comment by zhaoxin19** [comment]
刚看了一下，已经解决了，原来是我输入文件的文件名格式跟您的不一样，麻烦您了，非常感谢

**Comment by wuhuaming2006** [comment]
你跑通了是什么样的呢？我一直卡在下面不动，你跑了多久呢？
Solving...
I0614 15:07:34.769568  6664 solver.cpp:347] Iteration 0, Testing net (#0)

**Comment by zhaoxin19** [comment]
fc9_1: 0.0619729
loss: ap:0.568536 an:0.628876
I0614 15:24:00.319629 10555 solver.cpp:228] Iteration 560, loss = 0.0760857
I0614 15:24:00.319699 10555 solver.cpp:244]     Train net output #0: loss = 0.0760857 (* 1 = 0.0760857 loss)
I0614 15:24:00.319721 10555 sgd_solver.cpp:106] Iteration 560, lr = 0.05
fc9_1: 0.0619722
loss: ap:0.540275 an:0.890354
fc9_1: 0.0619728
loss: ap:0.452767 an:1.21622
fc9_1: 0.061971
loss: ap:0.881034 an:0.80138
fc9_1: 0.0619814
loss: ap:0.429369 an:0.828808
fc9_1: 0.0619875
loss: ap:0.798499 an:1.08327
fc9_1: 0.0619937
loss: ap:0.729071 an:1.82053
fc9_1: 0.0620082
loss: ap:0.817582 an:1.00206
fc9_1: 0.0620322
loss: ap:0.570284 an:0.704883
fc9_1: 0.0620538
loss: ap:0.481246 an:0.64945
fc9_1: 0.0620749
loss: ap:0.705009 an:0.967703
fc9_1: 0.0620933
loss: ap:0.502885 an:0.69869
fc9_1: 0.0620963

**Comment by zhaoxin19** [comment]
我是用5万张图像训练的，batch大了好像会崩掉，现在batch是60，跑得比较快，就是看着好像lr不往下降，然后好像还没太收敛

**Comment by wuhuaming2006** [comment]
你是用的train.prototxt 的VGG_FACE_16_layers网络跑的吗? 还是用的简单的网络

**Comment by zhaoxin19** [comment]
就是这个VGG16，我下的他的网络没改过

**Comment by wuhuaming2006** [comment]
请问你这个格式怎么改的？068c8d55a54daf5e2bf0874d0@068c8d55a54daf5e2bf0874d1077554480_0.jpg 559

我也出现了这个问题AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by chulaihunde** [comment]
I0614 14:30:08.994966 10091 solver.cpp:60] Solver scaffolding done.
Solving...
I0614 14:30:09.001552 10091 solver.cpp:337] Iteration 0, Testing net (#0)
Traceback (most recent call last):
File "train.py", line 92, in
sw.train_model(max_iters)
File "train.py", line 63, in train_model
self.solver.step(1)

File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 101, in forward
blobs = self._get_next_minibatch()
File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 57, in _get_next_minibatch
im_blob,labels_blob = self._get_image_blob(sample)
File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/datalayer.py", line 71, in _get_image_blob
im = prep_im_for_blob(im)
File "/data/zhaoxin/caffe/tripletloss/tripletloss/tripletloss/blob.py", line 31, in prep_im_for_blob
im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'



============
请问这个问题怎么解决的？

**Comment by LiuJinxue** [comment]
@chulaihunde  这个报错主要是因为im是None，应该是你的文件路径有问题读不到文件，或者说你的文件本身有问题无法读取

**Comment by louielu1027** [comment]
@zhaoxin19 您好，我想问一下他的trian_val.txt是什么格式？“人名@图片名  类别”吗？

**Comment by louielu1027** [comment]
@wuhuaming2006 您好，我的也是卡在那个地方不动
Solving...
I0817 15:43:24.764153 20758 solver.cpp:294] Iteration 0, Testing net (#0)

您是如何解决的呢？

**Comment by DaleGuo1995** [comment]
@louielu1027   那是因为你每个人的图片数量不够，在datalayer那层陷入了while死循环，你batch_size设的多少？每个人的图片数>=batch_size/3 + 1;
